Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss
=> [Add]installed gems & [Fix]modified scss

config/routes.rb
=> [fix]member-routes

app/controllers/application_controller.rb, app/views/members/registrations/new.html.erb
サインアップの項目増やしたよ
アプリケーションコントローラーも編集済み
=> Edit signup view

app/views/admins/sessions/new.html.erb
=> Tesut user delete

app/controllers/admin/members_controller.rb, app/models/order.rb, app/models/order_product.rb, app/views/admin/members/edit.html.erb, app/views/admin/members/index.html.erb, app/views/admin/members/show.html.erb, app/views/layouts/_error.message.html.erb
admin::membersコントローラ動きとしてほぼ完成
エラーメッセージの部分テンプレ作成
=> Order function

app/models/member.rb, app/views/members/registrations/new.html.erb
=> Fix member status

app/views/members/registrations/new.html.erb
=> Fix signup item

app/controllers/admin/genres_controller.rb, app/controllers/admin/products_controller.rb, app/models/genre.rb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb, app/views/admin/products/new.html.erb
=> Genre product new

app/models/product.rb, app/views/admin/products/edit.html.erb, app/views/admin/products/index.html.erb, app/views/admin/products/new.html.erb, app/views/admin/products/show.html.erb
=> image_reject

app/controllers/member/destinations_controller.rb, app/controllers/member/members_controller.rb, app/controllers/members/sessions_controller.rb, app/views/member/destinations/edit.html.erb, app/views/member/destinations/index.html.erb, app/views/member/members/edit.html.erb, app/views/member/members/quit.html.erb, app/views/member/members/show.html.erb, config/routes.rb
配送先コントローラー編集（pull後要確認）
メンバー退会処理設定
=> Hide action

Gemfile, Gemfile.lock, app/controllers/member/products_controller.rb, app/views/member/cart_products/index.html.erb, app/views/member/products/_list.html.erb, app/views/member/products/index.html.erb
=> Cartproduct product2

app/controllers/member/destinations_controller.rb, app/controllers/member/members_controller.rb, app/views/layouts/application.html.erb, app/views/member/destinations/edit.html.erb, app/views/member/destinations/index.html.erb, app/views/member/members/edit.html.erb
フラッシュメッセージ追加
エラーメッセージ追加
member/members_controller destinations_controller
=> Error message

app/controllers/member/cart_products_controller.rb, app/views/layouts/_header.html.erb, app/views/member/cart_products/index.html.erb, app/views/member/products/show.html.erb
=> cart_product_nosuke

app/views/admin/genres/edit.html.erb, app/views/admin/products/edit.html.erb, app/views/admin/products/show.html.erb
=> view-admin-product-show,edit

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/controllers/admin/members_controller.rb, app/controllers/admin/products_controller.rb, app/controllers/member/products_controller.rb, app/views/admin/members/index.html.erb, app/views/admin/products/index.html.erb, app/views/kaminari/_first_page.html.erb, app/views/kaminari/_gap.html.erb, app/views/kaminari/_last_page.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/member/products/_list.html.erb, app/views/member/products/index.html.erb, config/application.rb, config/initializers/kaminari_config.rb, config/locales/kaminari_ja.yml
=> ページネーション追加追加

app/views/layouts/_error.message.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/member/destinations/edit.html.erb, app/views/member/destinations/index.html.erb, app/views/member/members/show.html.erb, app/views/members/registrations/edit.html.erb, app/views/members/registrations/new.html.erb, app/views/members/sessions/new.html.erb
サインアップ画面にパスワード入力欄追加
その他メンバー関連のivew修正
=> Fix signup view

app/controllers/admin/orders_controller.rb, app/controllers/member/orders_controller.rb, app/views/admin/members/edit.html.erb, app/views/admin/members/index.html.erb, app/views/admin/members/show.html.erb, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb, app/views/member/orders/confirm.html.erb, app/views/member/orders/index.html.erb, app/views/member/orders/new.html.erb, app/views/member/orders/show.html.erb, app/views/member/orders/thanks.html.erb
Admin::membersとAdmin&Member::orders周りのViewを修正
=> [Fix]Modified Views

Gemfile, Gemfile.lock, app/assets/javascripts/password_resets.coffee, app/assets/stylesheets/password_resets.scss, app/controllers/admin/orders_controller.rb, app/controllers/application_controller.rb, app/controllers/member/destinations_controller.rb, app/controllers/member/members_controller.rb, app/controllers/password_resets_controller.rb, app/helpers/password_resets_helper.rb, app/mailers/member_mailer.rb, app/models/member.rb, app/views/admin/orders/index.html.erb, app/views/layouts/_header.html.erb, app/views/member/cart_products/index.html.erb, app/views/member_mailer/password_reset.html.erb, app/views/member_mailer/password_reset.text.erb, app/views/members/sessions/new.html.erb, app/views/password_resets/edit.html.erb, app/views/password_resets/new.html.erb, config/environments/development.rb, config/routes.rb, db/migrate/20200607140853_add_reset_to_members.rb, db/schema.rb, test/mailers/member_mailer_test.rb, test/mailers/previews/member_mailer_preview.rb
=> Edit admin top

app/assets/stylesheets/application.scss, app/controllers/admin/genres_controller.rb, app/views/member/products/_list.html.erb, app/views/member/products/index.html.erb
=> application.scss

app/assets/stylesheets/application.scss, app/views/layouts/_header.html.erb, app/views/member/members/top.html.erb
=> Fix header footer

app/controllers/admin/products_controller.rb, app/views/admin/genres/index.html.erb, app/views/admins/sessions/new.html.erb
=> Genre image view

app/controllers/member/cart_products_controller.rb, app/views/admin/products/edit.html.erb, app/views/admin/products/show.html.erb, app/views/member/products/show.html.erb
=> cart-product-controller

app/controllers/member/cart_products_controller.rb, app/controllers/member/orders_controller.rb, app/controllers/member/products_controller.rb, app/views/member/products/index.html.erb, app/views/member/products/show.html.erb
=> [Fix]product-controller

app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb, app/views/admin/products/edit.html.erb, app/views/admin/products/new.html.erb, app/views/admin/products/show.html.erb, app/views/member/cart_products/index.html.erb, app/views/member/orders/confirm.html.erb, app/views/member/products/show.html.erb
=> View edit nosuke

app/views/password_resets/new.html.erb
=> Cartproduct product8

app/assets/stylesheets/application.scss, app/views/admins/sessions/new.html.erb
=> admins/sessions view編集
